### ISSUE TITLE
Spike: Research Test Frameworks

### ISSUE THREAD

**Issue by BenGalewsky** [OpenTechStrategies/psm#204]
# Problem
As development continues on PSM we need automated testing tools to validate code quality.

# Tasks
In this spike research alternative frameworks for
- [x] Code Formatting and Quality standards
- [x] Unit testing of code modules
- [ ] Code coverage of tests
- [x] Integration testing of the deployed Web Application with Selenium

**Comment by jasonaowen** [comment]
I have previously used and liked [Spock](http://spockframework.org/) for unit tests, and would like to use it on this project. Groovy is a nice language to work in (and tests do not need to be so strict about language requirements, so even if we were tightly constrained to ship Java code - and I'm not sure that we are - I think this would be fine), and I have found Spock allows for very readable tests, particularly when using data tables.

**Comment by cecilia-donnelly** [comment]
I asked @slifty to look into integration testing in Java, while @BenGalewsky works on the Selenium tests for #218.

@jasonaowen, can you comment here (at more length) with your thoughts on the frameworks we should be using?  The focus of this issue is on setting up the _framework_ for tests, more than writing tests for code that may change or go away.  We just want to be ready to write tests when we start developing new functionality.

**Comment by jasonaowen** [comment]
Sure, I'm happy to.

In my experience, the difference between unit tests and integration tests is scope, running time, and set up; unit and integration tests frequently share a framework. As I mentioned before, [Spock](http://spockframework.org/) is a framework I've used and liked, and I suggest we use it in this project.

I strongly suggest that it would be useful to start with a very simple unit test to make sure the framework is installed correctly *before* trying to write any integration tests. This has value on its own (the ability to write unit tests!), but I also expect there will be some complexity in setting up the integration tests: likely candidates include database provisioning (can we use an in-memory database? Which one? How do we set that up?), web configuration (how do we meaningfully validate that an HTTP endpoint behaves the way we expect? Do we need to stand up an entire application server? Should it / does it have to be WildFly?), and Spring configuration (how much of Spring do we need to use? How do we configure it differently for tests?). Those points of complexity can be addressed incrementally as we add tests to different parts of the application, but we should do so separately and intentionally.

(Also, as a note on procedure, I would really appreciate a PR with just the framework addition & simple unit test, and a separate PR with integration test setup and first example.)

@slifty is that a useful amount of detail?

**Comment by slifty** [comment]
For the other framework explorations, this slideshow seems like a reasonable starting point: https://www.slideshare.net/SpringCentral/continuous-delivery-with-gradle-and-jenkins

**Comment by jasonaowen** [comment]
> For the other framework explorations, this slideshow seems like a reasonable starting point: https://www.slideshare.net/SpringCentral/continuous-delivery-with-gradle-and-jenkins

@slifty can you say more? There're a lot of slides there, and they seem to be a mix of CI 101 and very specific gradle patterns, plus probably more besides.

**Comment by brainwane** [comment]
I'd also like some clarity on how to configure things so that our test frameworks run tests both on the Java stuff and on other chunks of the codebase, e.g., the tests on James's ETL code. I imagine we'll be turning [manual testing steps on the ETL functionality](https://github.com/OpenTechStrategies/psm/pull/269#issuecomment-316511199) into automated tests written in Python, and it would be good to make sure all those tests get run fairly frequently.

**Comment by jasonaowen** [comment]
> our test frameworks run tests both on the Java stuff and on other chunks of the codebase

I imagine those would be run as a separate step in our continuous integration. Writing tests for Python code in Java, or vice versa, doesn't sound like a good time to me. :) We can add a line to our `.travis.yml` to run the Python tests.

I trust you all have stronger/better-informed opinions on Python test frameworks than I do!

**Comment by BenGalewsky** [comment]
I did some experimentation with Checkstyle.

It turns out that our current codebase almost checks out as-is with openjdk style.

The only issue I ran into was the ordering of imports, so I modified the ImportOrder module in the openjdk style config to say:
```
    <module name="ImportOrder">
      <!--<property name="groups" value="java, javax, org, com"/>-->
      <property name="ordered" value="false"/>
      <property name="separated" value="true"/>
    </module>
```

**Comment by jasonaowen** [comment]
On the first point, I have encountered three major style guides for Java: [OpenJDK](http://cr.openjdk.java.net/~alundblad/styleguide/index-v6.html), [Google](https://google.github.io/styleguide/javaguide.html), and [Twitter](https://github.com/twitter/commons/blob/master/src/java/com/twitter/common/styleguide.md). We should see how close our codebase is to each, and which we'd want our codebase to aspire to. @BenGalewsky has done some research on this (above).

**Comment by jasonaowen** [comment]
I think the code style issue is separate from our testing framework, which is in and working. I spun off #456, and am closing this.
